name: an_lifecycle_cancellable
description: "After merging Lifecycle and Cancellable, the toolkit provided in flutter"
version: 2.4.2
homepage: https://github.com/aymtools/lifecycle_cancellable/
issue_tracker: https://github.com/aymtools/lifecycle_cancellable/issues

topics:
  - lifecycle
  - anlifecycle
  - cancel
  - cancellable
  - remember

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cancellable: ^2.3.0
  anlifecycle: ^3.3.0
  weak_collections: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.15

  flutter_lints: ^5.0.0

